POST http://localhost:3333/clients
Content-Type: application/json

{
  "cpf": "000.999.999.00",
  "name": "Leo Dias",
  "email": "leo@example.com",
  "address": "Rua 133 Nª90, São Paulo",
  "workplace": "Arvox",
  "profession": "PO"
}

######


GET http://localhost:3333/clients


######

GET http://localhost:3333/clients/67208853-b4e6-4b86-94f8-123bcca26d4c

######



PUT  http://localhost:3333/clients/67208853-b4e6-4b86-94f8-123bcca26d4c
Content-Type: application/json

{
  "cpf": "999.999.999.00",
  "name": "Sara Cruz",
  "email": "sara@arvox.com",
  "address": "Rua Eldorado Nª50, Cidade Nova",
  "workplace": "Arvox",
  "profession": "Design"
}



######

DELETE http://localhost:3333/clients/0f841dcc-ee2d-48fc-b458-950fa275bcf5
