POST http://localhost:3333/clients
Content-Type: application/json

{
  "cpf": "999.999.999.99",
  "name": "Sara Santos",
  "email": "saea@santos.com",
  "address": "Rua Eldorado Nª50",
  "workplace": "Arvox",
  "profession": "Design"
}

######

GET http://localhost:3333/


######

GET http://localhost:3333/clients/67208853-b4e6-4b86-94f8-123bcca26d4c